# Site settings
title: Meadow View Farms | Bed & Breakfast | For Sale
email: info.meadowviewfarm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Meadow View Farm, Bed and Breakfast, is now for sale. Please visit the Realtor.com link for more information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meadowviewfarm.info/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
